language: python
python:
- '3.6'
install:
- pip install xml2rfc
script:
- xml2rfc --html draft-ytti-intarea-icmp-eo-timestamp.xml
- xml2rfc --text draft-ytti-intarea-icmp-eo-timestamp.xml
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$ICMP_EO_TIMESTAMP_GH_PAGES_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: TUzuveW2CBVwQ+bbuDCAqitu6Q5InFSGWTDB8N6VI7LLIfuAAvOrm6aUkGUWLBcvQ57G2oRt2PuG0zWlM0pRttGu3pZ6SjN16itUYuFvq739lcUOQFeLvM8vneTNdA5xg+DPUJSr9UBcR04xVniHKhY4d0M6yuPnExrEvA91P5zY3geDYYqqPBUaIwGrQvfNs5fj9sKxgK2buFiSF7qihcvLv4ivuS94HjpIgUWnk8QjMjY7S+FdEbSdGbrqdUoT6YOmVrm30AT4oWvWIJGECeZCP5ikwoi1nBirEjWHdqB9YgIU2QTTZHuxa0LfqBp2sqocVl8ttw2viUODVbL0lUjBQ+vU9pCPWM6mDsMcBwI4qfYxtYwz5SrzdX/EREXO/DiEThX2FjFT9e7DszmcnSpqVegAhR1UCu+jxeCW1fVAbYwB2a+65E3l55rnTFyREYCPJvnVY+i5oHRUsmnhNwME2kcIjodCQsmUEFiBfzuAA+SpIWZ0qMFW8Tn5Onu9whfAf95Jr5veS1IHBbt+voWAn5+JseOqnJKkVhFt7FsuiadJZFOzFeMUkhSz7/3IjnqeThztGgIbH+eUsDR1p9w1kC6+j1W0fxgLvDd7uKADr8EcOyhbCoHzOBrxM4n70PmdgwYjsgo7rYPYet9EOzlSeFYVZBZdnfwfa2vRuh8=
